FF_CONFIGURE="--enable-gpl --enable-version3 --disable-debug"
FF_CFLAGS="-O3 -pipe -march=x86-64-v3"
FF_CXXFLAGS="-O3 -pipe -march=x86-64-v3"
FF_LDFLAGS="-O3 -pipe -march=x86-64-v3"
GIT_BRANCH="master"
LICENSE_FILE="COPYING.GPLv3"
